### PR TITLE
Join a lunch Screen

### PR DESCRIPTION
**Pull request by wassertim**
- [ ] add items
- [ ] add tests

### CODE REVIEW

**Comment by SadatAnwar** [comment]
@wassertim we have wip labels ;)

**Comment by wassertim** [comment]
@SadatAnwar yep :) thanks

**Comment by wassertim** [comment]
I'd like to merge this, and continue on Tests, Services for this issue in a different branch. @SadatAnwar please review

**Comment by wassertim** [comment]
screen shot 2016-09-04 at 11 07 34

**Comment by SadatAnwar** [comment]
👍 looks great! go go go

**Pull request merged**
