### PR TITLE
added webjar play and j-query

### PR DESCRIPTION
**Pull request by SadatAnwar**
some minor adjustments to the build sbt to get jquery 
@wassertim @cbertilsson this is small and I need in fornt-end so a very quick approval please :)

### CODE REVIEW

**Comment by wassertim** [comment]
Whaaaaat? jquery whyyyyy?

**Comment by wassertim** [comment]
Take it easy please :|

**Comment by SadatAnwar** [comment]
@wassertim no? for some animations ? ah okay Ill remove to :)

**Comment by SadatAnwar** [comment]
@wassertim removed :) (I had used it once, so thought it would be easy, but you are right, not needed) now please approve :)

**Comment by wassertim** [comment]
we are using angular. and it has everything for animations and other things

**Pull request merged**
