### PR TITLE
Setup travis ci

### PR DESCRIPTION
**Pull request by SadatAnwar**

### CODE REVIEW

**Comment by SadatAnwar** [comment]
build it

**Comment by SadatAnwar** [comment]
@wassertim I have added the CI bit, but its failing, and I am not sure why! But I think it has something to do with npm? Could you please take a look at the build job?

**Comment by wassertim** [comment]
Yahoooooooooo :))))

**Comment by wassertim** [comment]
@SadatAnwar We can merge this

**Comment by SadatAnwar** [comment]
WHAAAT!!!!!!!!!! how did you do that!! You are AWESOME!!! YOU ARE THE BEST!

**Comment by wassertim** [comment]
Just look into commits :)

**Comment by SadatAnwar** [comment]
I saw! This is stuff only you can understand! But looks great the build passing bit

**Comment by SadatAnwar** [comment]
But wait, will travis also run our scala build and tests? I think we will need to configure it! We should definitely meet up! this weekened at least for an hour

**Comment by wassertim** [comment]
yes, let’s meet up on Sunday

**Comment by SadatAnwar** [comment]
I call you today, later 
maybe I can meet for a bit after work? In the evening

**Pull request merged**
