### PR TITLE
Add editorconfig

### PR DESCRIPTION
**Pull request by wassertim**
That is essential for an opensource project

### CODE REVIEW

**Comment by wassertim** [comment]
@SadatAnwar ping

**Comment by SadatAnwar** [comment]
what is this? and why?

**Comment by wassertim** [comment]
this is a configuration file for all the IDEs. If I use Atom and you use Intellij - we always have the same indentation styles. That's why it should be in the project

**Comment by SadatAnwar** [comment]
ah!! good good good!! 👍  go for it

**Pull request merged**
